### ISSUE TITLE
ListView in Modals don't work properly in with forceToFront

### ISSUE THREAD

**Issue by dhrrgn** [brentvatne/react-native-modal#11] opened 2015-04-24 14:30 UTC
In our Modal we have a `<ListView>` inside it, with a set height.  With `forceToFront` set to `false`, the list scrolls correctly. However, when we set `forceToFront` to `true`, the list no longer scrolls.

Internally, a ListView is implemented as a ScrollView containing Views, so I suspect the issue is actually with the ScrollView.

**Comment by brentvatne** [comment] 2015-04-24 17:54
@dhrrgn - interesting, I hadn't tried combining these yet, if you have a chance to try to debug it that would be great, otherwise I can probably look at it this weekend :smile:

**Comment by dhrrgn** [comment] 2015-04-27 21:38
@brentvatne Sorry, I did not have a chance to look at it yet. I will take a look tomorrow though and see what I can come up with.  I am not sure whether the bug is in `Modal` or `Overlay`, so this issue may be in the wrong project.

**Comment by brentvatne** [comment] 2015-04-28 03:02
@dhrrgn - No problem. I think the issue is _probably_ with Overlay, take your time as it looks like nobody else has run into this issue yet. Thanks a lot!

**Comment by dhrrgn** [comment] 2015-04-30 22:40
@brentvatne I took a look and couldn't figure it out.  However, I can be fairly certain the issue in the Obj-C side of things, as I have tried everything I thing I can think of in the `Overlay.ios.js` stuff.  I suspect it has something to do with the way the subviews are put into the new UIWindow?  Maybe?

**Comment by brentvatne** [comment] 2015-04-30 23:41
@dhrrgn - seems likely, I'll add it to a list of things to look at this weekend, thanks for checking it out!

**Comment by brentvatne** [comment] 2015-05-03 03:38
@dhrrgn - yeah this is a tricky one, couldn't figure it out :( It looks like the height of the ScrollView isn't properly being set - notice that with `forceToFront` as true there is no scrollbar

**Comment by rxb** [comment] 2015-05-13 21:52
Not sure if this is a useful data point, but it looks like it also happens just when using the Overlay on its own.

**Comment by brentvatne** [comment] 2015-05-17 04:55
@rxb - thanks for the info, I noticed the same thing on my end

**Comment by Furizaa** [comment] 2015-05-20 20:20
+1

I would try to help if I could. But sadly I have absolutely no idea what is happening on the iOS side of things.

**Comment by brentvatne** [comment] 2015-05-25 03:57
@Furizaa @dhrrgn @rxb - fixed with `react-native-overlay` 0.2.2, should work with 0.3.5 of this lib :smile:

**Closed as completed by brentvatne** 2015-05-25 03:57 UTC
Labels: bug, help wanted

**Comment by dhrrgn** [comment] 2015-05-25 14:36
Awesome. Thanks @brentvate (and @johanneslumpe).

**Comment by rxb** [comment] 2015-05-26 00:24
Thanks!
